### ISSUE TITLE
welcome screen punctuation

### ISSUE THREAD

**Issue by lchamber-luc** [ryanmark1867/chatbot#20]
punctuation that needs to be fixed:
- add comma after "hello" and after first name.  e.g. "Hello, Luc, I'm Movie Molly!"
- welcome appears as two text messages (see screen cap).  need to combine these.

![image](https://user-images.githubusercontent.com/56003398/71330833-212acb80-24fd-11ea-8f23-1a9a21c96b39.png)

**Comment by ryanmark1867** [comment]
Punctuation fixed:
![image](https://user-images.githubusercontent.com/39224115/71382134-900f2f80-25a4-11ea-819f-30594cdbb894.png)

Welcome text cannot be combined - quick response must have text associate with it, and text cannot be blank.
