### ISSUE TITLE
can't find genre

### ISSUE THREAD

**Issue by lchamber-luc** [ryanmark1867/chatbot#22]
getting "empty result - please try another query" from the following submission:

"genre of One Hundred and One Nights"

**Comment by ryanmark1867** [comment]
there is no movie with this (original) title in the database. You should search the correct title "Les cent et une nuits de Simon Cinéma":

![image](https://user-images.githubusercontent.com/39224115/71728903-6e1b7580-2e0c-11ea-86af-be94b2f7f47f.png)

searching the "Title" column as well as the "original title" field for titles is beyond the scope of Demo 1. I will open a separate feature requirement to add this new function post Demo 1.

**Comment by lchamber-luc** [comment]
Agreed.
