### ISSUE TITLE
can't find Genre

### ISSUE THREAD

**Issue by lchamber-luc** [ryanmark1867/chatbot#23]
getting the following "empty result - please try another query" after submitting:

"genre of Drew: The Man Behind the Poster"

**Comment by ryanmark1867** [comment]
"Drew: The Man Behind the Poster" doesn't exist in the data set we use. The original record was corrupted (either missing key fields of having JSON fields that were corrupted), so there is no record for this movie in the database we use.

**Comment by lchamber-luc** [comment]
Looking in movies_metadata.csv, both the title and original title have the same value ("Drew: The Man Behind the Poster").  Look in the file with movie ID 213831
