### ISSUE TITLE
server not responding

### ISSUE THREAD

**Issue by lchamber-luc** [ryanmark1867/chatbot#31]
after move to Azure, some regressions:

1) input: "plot for blade runner".   output: "query generated error - please continue with next query"
2) input: "comedy".  output: a set of dynamic links, but took a long term to come up.
3) input: "Deadpool (2016)".   output:  no response.

possibly related to server timing out, or issue with error handling.

**Comment by ryanmark1867** [comment]
Repro steps for error 1:
1. delete conversation
2. Hi
3. Genre
4. Adventure
5. what year was blade runner

Bot goes away for a while then returns "query generated error - please continue with next query"

Python message:

IN CONDITION BY MOVIE

"2020-01-25 15:57:19 WARNING  root  - RESULT IS      year
512  1982
2020-01-25 15:57:19 WARNING  root  - exception not generated
2020-01-25 15:57:19 WARNING  root  - number of rows in result 1
2020-01-25 15:57:19 WARNING  root  - result is      year
512  1982
2020-01-25 15:57:19 WARNING  root  -  1982
2020-01-25 15:57:19 WARNING  root  - payload_text is show details for 1982
2020-01-25 15:57:19 WARNING  root  - exception generated single positional indexer is out-of-bounds"

no issues if context not switched.

Problem seems to be here;

if tracker.get_slot('detail_mode') == 'text_list':

detail_mode is not getting reset correctly if the user switches from the script context to simple back and forth

**Comment by ryanmark1867** [comment]
summary of live flow that leads to the above error:

![image](https://user-images.githubusercontent.com/39224115/73124972-8bf17b80-3f6f-11ea-9208-4dcf52262d7b.png)

**Comment by ryanmark1867** [comment]
1. input: "plot for blade runner". output: "query generated error - please continue with next query"
2. input: "comedy". output: a set of dynamic links, but took a long term to come up.
3. input: "Deadpool (2016)". output: no response.

Of these:
1. is a legit issue but not critical path for demo 1. I'll fix it post demo 1 being done. New defect is: https://github.com/ryanmark1867/chatbot/issues/33
2: not repro-able. Overall performance tracked with this defect https://github.com/ryanmark1867/chatbot/issues/25
3. up until today this was a dead-end in the code, to behaviour not unexpected. Now this code path brings up default page in webview.
