### ISSUE TITLE
movie run time field formatting

### ISSUE THREAD

**Issue by lchamber-luc** [ryanmark1867/chatbot#38]
Under the title of Blade Runner in web view, text indicates "Run Time" as "117.0".  suggest truncating to integer and adding unit (e.g., "117 min"), or better still, indicate in hours/min (e.g., "1h 57min"), which is what IMDb does

**Comment by ryanmark1867** [comment]
Fixed for demo 1 - hack that will need to be revisited post demo 1:

![image](https://user-images.githubusercontent.com/39224115/75637157-8af8dd00-5bf2-11ea-9fc6-ca1dae64873b.png)
